"use client";

import { useState } from "react";
import { MessageCircle, X } from "lucide-react";
import Link from "next/link";

export default function WhatsAppButton() {
  const [isOpen, setIsOpen] = useState(false);

    return (
        <div className="fixed bottom-6 right-6 z-50">
              {/* Chat Bubble */}
                    {isOpen && (
                            <div className="mb-4 bg-white rounded-2xl shadow-2xl border border-gray-200 p-4 w-72 animate-in slide-in-from-bottom-4 fade-in duration-300">
                                      <div className="flex items-start justify-between mb-3">
                                                  <div className="flex items-center gap-2">
                                                                <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-full flex items-center justify-center">
                                                                                <MessageCircle className="w-5 h-5 text-white" />
                                                                                              </div>
                                                                                                            <div>
                                                                                                                            <div className="font-semibold text-gray-900 text-sm">
                                                                                                                                              Nurse Eunice
                                                                                                                                                              </div>
                                                                                                                                                                              <div className="text-xs text-gray-500">Usually replies instantly</div>
                                                                                                                                                                                            </div>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                  onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                className="p-1 hover:bg-gray-100 rounded-full transition"
                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                          <X className="w-4 h-4 text-gray-500" />
                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                          <div className="bg-emerald-50 rounded-lg p-3 mb-3">
                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-gray-700 leading-relaxed">
                                                                                                                                                                                                                                                                                                                                    👋 Hello! How can I help you today? Chat with me on WhatsApp for
                                                                                                                                                                                                                                                                                                                                                  quick assistance.
                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                  <Link
                                                                                                                                                                                                                                                                                                                                                                                              href="https://wa.me/2349167187407?text=Hello%20Nurse%20Eunice%2C%20I%20need%20help%20with..."
                                                                                                                                                                                                                                                                                                                                                                                                          target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                      rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                  className="block w-full text-center px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg font-medium text-sm transition shadow-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Start Chat on WhatsApp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs text-gray-500 text-center mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        We typically reply within minutes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Floating Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => setIsOpen(!isOpen)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-14 h-14 bg-emerald-600 hover:bg-emerald-700 text-white rounded-full shadow-2xl flex items-center justify-center transition-all hover:scale-110 active:scale-95"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    aria-label="Chat on WhatsApp"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {isOpen ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <X className="w-6 h-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <MessageCircle className="w-6 h-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Notification Badge */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {!isOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="absolute top-0 right-0 w-4 h-4 bg-red-500 rounded-full border-2 border-white animate-pulse" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            